services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    restart: always
    networks:
      - chatbot

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - chatbot


  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    entrypoint: >
      sh -c "ollama serve & sleep 3 && ollama run llama3 && tail -f /dev/null"
    networks:
      - chatbot


volumes:
  ollama_data:

networks:
  chatbot:
    driver: bridge